Mock everything (#70)
* Add support for mocking functions and objects via generated types

* Fix altered generated import

* Revert "Fix altered generated import" as a test

This reverts commit 25baa4f4ebb1c77eb0450f331407af697fc2a247.

* Move gen code check to after tests run (some test gen mocks)

* Revert "Revert "Fix altered generated import" as a test"

This reverts commit 4968e529299fa9084bfccdb3a47960c6f71dc96d.

* Quash/appease linters

* Spruce up unit tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -32,13 +32,6 @@ jobs:
           go generate ./...
           MOQ_DEBUG=true moqueries bulk-finalize
 
-          # fail if working directory is dirty
-          git status --short
-          if [[ -n $(git status --short) ]]; then
-            echo "Working directory dirty"
-            exit 1
-          fi
-
     - run:
         name: Run tests
 
@@ -49,6 +42,20 @@ jobs:
             -race -covermode=atomic -coverprofile=coverage.out $PACKAGE_NAMES
           go install golang.org/x/vuln/cmd/govulncheck@latest
           govulncheck ./...
+
+    - run:
+        name: Check generated code
+
+        command: |
+          set -ux
+          # fail if working directory is dirty
+          # Note: We check after Generate code *and* Run tests because some
+          #   tests generate mocks too.
+          git status --short
+          if [[ -n $(git status --short) ]]; then
+            echo "Working directory dirty"
+            exit 1
+          fi
 
     - codecov/upload
 
