Add support for bulk operations (#42)
* Add support for bulk operations

* Fix mktemp

* Fixup tests

* Fix dirty working dir check

* Add missing file (for dirty working dir check)

* Fix dirty working dir check

* Update readme with bulk docs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,8 +25,19 @@ jobs:
 
         command: |
           set -ux
+          find . -name moq_\*.go -delete
           go build -o $GOPATH/bin/moqueries github.com/myshkin5/moqueries
+          export MOQ_BULK_STATE_FILE=$(mktemp --tmpdir= moq-XXXXXX)
+          moqueries bulk-initialize
           go generate ./...
+          MOQ_DEBUG=true moqueries bulk-finalize
+
+          # fail if working directory is dirty
+          git status --short
+          if [[ -n $(git status --short) ]]; then
+            echo "Working directory dirty"
+            exit 1
+          fi
 
     - run:
         name: Run tests
